name: Lint

on: [push, pull_request]

jobs:
  lint-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: cd /apps/client && npm ci

      - name: Run lint
        run: cd /apps/client && npm run lint

  lint-api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: cd /apps/api && npm ci

      - name: Run lint
        run: cd /apps/api && npm run lint
